/**
 * esbuild build script for dsh-johari-cognition-quadrant-dialog-composer.
 *
 * Builds two ESM bundles:
 *   - src/index.ts       → lib/index.js  (host half, no deps bundled)
 *   - src/client/index.ts → lib/client.js (browser half, react/react-dom external,
 *                              CSS imported as text and injected at runtime)
 *
 * Usage: node scripts/build.mjs
 */
import { build } from 'esbuild'
import { readFileSync, rmSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const outDir = resolve(root, 'lib')
const clientTemp = resolve(outDir, 'client.cjs')

rmSync(outDir, { recursive: true, force: true })
mkdirSync(outDir, { recursive: true })

const commonOptions = {
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  sourcemap: true,
  logLevel: 'info',
}

await build({
  ...commonOptions,
  entryPoints: [resolve(root, 'src/index.ts')],
  outfile: resolve(outDir, 'index.js'),
  banner: {
    js: '// dsh-johari-cognition-quadrant-dialog-composer host half — generated by esbuild. Do not edit.',
  },
})

await build({
  ...commonOptions,
  entryPoints: [resolve(root, 'src/client/index.ts')],
  outfile: clientTemp,
  format: 'cjs',
  platform: 'browser',
  sourcemap: false,
  external: ['react', 'react-dom', 'react/jsx-runtime'],
  loader: { '.css': 'text' },
})

const clientModule = readFileSync(clientTemp, 'utf8')
rmSync(clientTemp, { force: true })
writeFileSync(
  resolve(outDir, 'client.js'),
  `window.__ModuleLoader__.load({\n\tid: "dsh-johari-cognition-quadrant-dialog-composer",\n\tfactory: (require) => {\n\t\tvar module = { exports: {} };\n\t\tvar exports = module.exports;\n${clientModule}\n\t\treturn module.exports;\n\t}\n});\n`,
)

console.log('\nBuild complete: lib/index.js, lib/client.js')
